### ISSUE TITLE
client and server time not in sync

### ISSUE THREAD

**Issue by MrPrezident** [vrpn/vrpn#101] opened 2015-08-23 22:30 UTC
Sometimes when I do vrpn_gettimeofday() inside one of the callback handlers on the client, the msg_time is later than the time from vrpn_gettimeofday().  This is problematic as my application requires that the timestamps are accurate.  I thought that vrpn was supposed to keep times in sync somehow.  Is that not true?

**Comment by russell-taylor** [comment] 2015-08-23 23:27
I presume that you're running this on Windows, and both of the threads are on the same host.  If so, this is a repeat of issue #27.  There is a problem using the performance timer on Windows when there is more than one processor core.  There are some notes on that issue about how we might fix it, but if someone has experience with this we'd love to have help.

If the jobs are on different hosts, the recent versions of VRPN rely on the system clocks to be synchronized using NTP to within the desired accuracy.  Early versions of VRPN had an internal clock-shift estimator, but the folks who developed NTP are much more experienced at this than we are so we switched.

**Comment by MrPrezident** [comment] 2015-08-23 23:51
The servers are on linux.  The client is on OS X.

**Comment by MrPrezident** [comment] 2015-08-23 23:58
Also, when I noticed this, it was when I was trying to demo my project over wifi at a conference with about 5,000 developers, so the wifi was a bit congested.  I was expecting lots of latency and packet loss, but I did not expect the timestamp from the server message to be later than the time it was received at the client.

**Comment by russell-taylor** [comment] 2015-08-24 00:11
Okay, then this is a different issue than 27.  It looks like the clocks on the different systems were set at different times,with the one on the server shifted later relative to the one on the client machine.

The timestamps should still give accurate relative times (two times from the same Linux server should have the correct interval).  Some VRPN device drivers do a more careful job of determining the actual time, and others just record the time that the report was presented to VRPN, but in either case intervals should be preserved.

But VRPN does rely on the clocks on the different hosts to be synchronized if it is important that the messages from different hosts (or between client and server) need to be consistent.

We're running into this issue with OSVR as we start using predictive trackers, and we'll need to deal with it somehow -- this is how bug 27 came to be noticed...

**Comment by russell-taylor** [comment] 2017-06-24 17:42
I'm assuming that this issue is caused by clock drift on the two machines.  The solution is to use ntp to synchronize the host clocks.  Closing this issue.  Please re-open if the issue is something else.

**Closed by russell-taylor** 2017-06-24 17:42 UTC
